import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./ui/components/Sidebar";

import OrderList from "./orderList/page";
import Navbar from "./ui/components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "page2",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="flex">
          <Sidebar />
          {/* w-full h-full min-h-[calc(100vh-64px)] bg-gray-100 text-gray-600 overflow-y-auto */}
          <main className="w-screen h-screen min-h-[calc(100vh-120px)] bg-gray-100 text-gray-600 overflow-y-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
